name: Publish slic-php80 docker image

on:
  push:
    branches:
      - main
      - '[0-9]+.[0-9]+.[0-9]+'
  release:
    types: [published]

env:
  IMAGE_NAME: ${{ github.repository }}-php80

jobs:
  publish-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for image
        id: meta
        uses: docker/metadata-action@v4.0.1
        with:
          images: ghcr.io/${{ env.IMAGE_NAME }}
          tags: |
            type=edge,branch=main
            type=ref,event=branch
            type=ref,event=tag
            type=semver,pattern={{raw}}

      - name: Change Dockerfile to php8.0
        run: "sed -i 's/7.4.29/8.0.20/g' containers/slic/Dockerfile"

      - name: Build and push image
        uses: docker/build-push-action@v3.1.1
        with:
          context: containers/slic
          file: containers/slic/Dockerfile
          push: true
          tags: |
            ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}